name: workflow-1
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - '!README.md'
jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    env:
      MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
      MONGO_USERNAME: "superuser"
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version - 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache NPM
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm test

    - name: Store Test Results
      uses: actions/upload-artifact@v4
      with:
        name: mocha-test-results
        path: test-results.xml

    - name: Code Coverage
      continue-on-error: true
      run: npm run coverage

    - name: Store Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-results
        path: coverage
        retention-days: 7

  containerization:
    name: Containerization
    permissions:
        packages: write
    needs: unit-testing
    env:
      GITHUB_USER: ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
    - name: Downcase REPO
      id: lowercase-repo
      run: |
        echo "github_repo=${GITHUB_REPOSITORY@L}" >> "${GITHUB_OUTPUT}"

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: GHCR Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ steps.lowercase-repo.outputs.github_repo }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: GHCR Push
      uses: docker/build-push-action@v6.10.0
      env: 
        GHCR_REPO: ghcr.io/${{ steps.lowercase-repo.outputs.github_repo }}
      with:
        context: .
        push: true
        tags: |
          "${{ env.GHCR_REPO }}:${{ github.sha }}"
          "${{ env.GHCR_REPO }}:latest"
