name: workflow-1
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    env:
      MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
      MONGO_USERNAME: "superuser"
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version - 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm test

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mocha-test-results
        path: test-results.xml
